name: Db Clean
on:
  workflow_dispatch:
    inputs:
      file_link:
        description: 'Input file link'
        required: true
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download file
        id: download
        run: |
          url="${{ github.event.inputs.file_link }}"
          huh="$(basename "$url" | sed 's/\&.*//')"
          curl -JO -L "$url"
          gzip -d "$huh"
          echo "$huh"
          
      - name: Run scripts
        run: |
          filename="$(echo "$huh" | sed 's/\.gz$//')"
          echo $filename
          apt update -y && apt install npm -y
          npm i fs readline
          node saver.js "$filename" &&
          node linkedin0.js &&
          node linkedin2.js &&
          node linkedin3.js
             
